### ISSUE TITLE
Erro grave ao desabilitar a opção b2b de uma loja b2c

### ISSUE THREAD

**Issue by brasiliadesigndf** [vtex-apps/store-discussion#482]
** Descreva o bug **
Uma descrição clara e concisa do que é o bug.

**Reproduzir**
Passos para reproduzir o comportamento:

Estou lançando minha primeira loja em IO e quando alterei a opção que está em CMS .. LOJA  B2B, o site simplesmente sai do ar.
se eu deletar um plugin no ambiente master e recriar o workspace da erro. Eu tenho outro ambiente que eu administro
em outro site e fiz alguns testes e funcionou perfeitamente. Então cheguei a uma conclusão que este primeiro que eu citei,
está com algum defeito que eu não consigo arrumar e no manual do vtex.io diz que se a gente tem algum problema é só 
abrir um ticken, só que a analista do suporte diz que não tem acesso para acessar está  área. E o projeto? Como eu fico? 
Tem como ajudar a resolver esse problema? tem como resetar e criar um novo? Creio eu que isso ocorreu na mudança de 
edição, mas eu não tenho acesso.

**Comportamento esperado**
O  comportamento esperado é que o sistema funcione o minimo para o desenvolvedor

** Ambiente de trabalho (preencha as seguintes informações, se aplicável): **

```
Error: Network error: Response not successful: Received status code 400
at new ApolloError (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:2759:28)
at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:3941:40
at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:4253:25
at Set.forEach (<anonymous>)
at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:4251:32
at Map.forEach (<anonymous>)
at QueryManager.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/apollo-client/bundle.esm.js.QueryManager.broadcastQueries (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:4249:22)
at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:3855:47
From previous event:
at ObservableQuery.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/apollo-client/bundle.esm.js.ObservableQuery.result (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:2808:16)
at QueryData.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/@apollo/react-hooks/lib/react-hooks.esm.js.QueryData.fetchData (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:814:44)
at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1392:39
From previous event:
at RenderPromises.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/@apollo/react-hooks/lib/react-hooks.esm.js.RenderPromises.addQueryPromise (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1391:64)
at QueryData.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/@apollo/react-hooks/lib/react-hooks.esm.js.QueryData.getExecuteSsrResult (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:862:45)
at QueryData.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/@apollo/react-hooks/lib/react-hooks.esm.js.QueryData.execute (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:793:21)
at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1067:95
at useDeepMemo (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1041:42)
at useBaseQuery (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1067:18)
at useQuery (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1086:12)
at Query (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:161:86)
at processChild (/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom-server.browser.development.js:3195:14)
at resolve (/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom-server.browser.development.js:3118:5)
at ReactDOMServerRenderer.render (/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom-server.browser.development.js:3541:22)
at ReactDOMServerRenderer.read (/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom-server.browser.development.js:3500:29)
at renderToStaticMarkup (/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom-server.browser.development.js:4074:27)
at process (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1463:20)
From previous event:
at getMarkupFromTree (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1468:30)
at getDataFromTree (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1452:12)
at getDataFn (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:17989:81)
at renderToStringWithData (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:17993:10)
at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:18116:22
at processTicksAndRejections (internal/process/task_queues.js:97:5)
From previous event:
at _callee$ (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:18115:103)
at tryCatch (/_v/public/assets/v1/npm/regenerator-runtime@0.11.1/runtime.js:63:40)
at Generator.invoke [as _invoke] (/_v/public/assets/v1/npm/regenerator-runtime@0.11.1/runtime.js:297:22)
at Generator.prototype.<computed> [as next] (/_v/public/assets/v1/npm/regenerator-runtime@0.11.1/runtime.js:115:21)
at asyncGeneratorStep (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:294:24)
at _next (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:316:9)
at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:323:7
From previous event:
at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:312:12
at render (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:18135:17)
at Object.start (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:18218:30)
at start (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:18964:35)
at Module../react/index.tsx (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:18972:3)
at __webpack_require__ (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:86:30)
at requireEntry (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/index.js:14:10)
at tryLoadModule (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:1710:13)
at lazyLoad (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:1722:12)
at register (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:1729:24)
at Module.<anonymous> (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/index.js:19:136)
at Module.../index.js (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/index.js:24:30)
at __webpack_require__ (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:86:30)
at checkDeferredModules (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:47:23)
at Array.webpackJsonpCallback [as push] (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:34:19)
at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/index.js:2:111
at Script.runInContext (vm.js:131:20)
at VM.run (/usr/local/data/service/node_modules/vm2/lib/main.js:208:72)
at /usr/src/node/middleware/render.ts:81:57
"root":{10 items
"graphQLErrors":[]0 items
"networkError":{7 items
"name":string"ServerError"
"response":{4 items
"headers":{}0 items
"timeout":int15000
"status":int400
"url":string"http://desenv--quatroondas.myvtex.com/_v/segment/graphql/v1?workspace=desenv&maxAge=medium&appsEtag=remove&domain=store&locale=pt-BR&__bindingId=4fa727b7-2ce4-40c2-8fc2-2ed20e2aa648&operationName=category&variables=%7B%7D&extensions=%7B%22persistedQuery%22%3A%7B%22version%22%3A1%2C%22sha256Hash%22%3A%22d58bb38328b74811a81481420630d6279bc30de4fe040f043635f756892904ae%22%2C%22sender%22%3A%22vtex.menu%402.x%22%2C%22provider%22%3A%22vtex.store-graphql%402.x%22%7D%2C%22variables%22%3A%22eyJpZCI6IiJ9%22%7D"
}
"statusCode":int400
"result":{1 item
"errors":[1 item
0:{3 items
"message":string"Request failed with status code 400"
"name":string"Error"
"stack":string"Error: Request failed with status code 400 at createError (/usr/local/app/node_modules/axios/lib/core/createError.js:16:15) at settle (/usr/local/app/node_modules/axios/lib/core/settle.js:17:12) at IncomingMessage.handleStreamEnd (/usr/local/app/node_modules/axios/lib/adapters/http.js:236:11) at IncomingMessage.emit (events.js:323:22) at endReadableNT (_stream_readable.js:1204:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
]
}
"message":string"Response not successful: Received status code 400"
"stack":string"ServerError: Response not successful: Received status code 400 at throwServerError (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:4941:17) at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:4966:13 at Object.base.apply (/usr/local/data/service/node_modules/vm2/lib/contextify.js:158:34) at processTicksAndRejections (internal/process/task_queues.js:97:5) From previous event: at QueryManager.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/apollo-client/bundle.esm.js.QueryManager.fetchRequest (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:4323:16) at QueryManager.<anonymous> (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:3840:50) at step (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:11649:23) at Object.next (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:11630:53) at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:11623:71 From previous event: at __awaiter (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:11619:12) at QueryManager.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/apollo-client/bundle.esm.js.QueryManager.fetchQuery (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:3786:71) at QueryManager.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/apollo-client/bundle.esm.js.QueryManager.observeQuery (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:4154:21) at ObservableQuery.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/apollo-client/bundle.esm.js.ObservableQuery.setUpQuery (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:3084:22) at ObservableQuery.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/apollo-client/bundle.esm.js.ObservableQuery.onSubscribe (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:3062:18) at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:2792:26 at new Subscription (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:12104:34) at ObservableQuery.subscribe (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:12183:14) at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:2822:38 From previous event: at ObservableQuery.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/apollo-client/bundle.esm.js.ObservableQuery.result (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:2808:16) at QueryData.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/@apollo/react-hooks/lib/react-hooks.esm.js.QueryData.fetchData (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:814:44) at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1392:39 From previous event: at RenderPromises.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/@apollo/react-hooks/lib/react-hooks.esm.js.RenderPromises.addQueryPromise (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1391:64) at QueryData.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/@apollo/react-hooks/lib/react-hooks.esm.js.QueryData.getExecuteSsrResult (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:862:45) at QueryData.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/@apollo/react-hooks/lib/react-hooks.esm.js.QueryData.execute (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:793:21) at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1067:95 at useDeepMemo (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1041:42) at useBaseQuery (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1067:18) at useQuery (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1086:12) at Query (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:161:86) at processChild (/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom-server.browser.development.js:3195:14) at resolve (/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom-server.browser.development.js:3118:5) at ReactDOMServerRenderer.render (/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom-server.browser.development.js:3541:22) at ReactDOMServerRenderer.read (/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom-server.browser.development.js:3500:29) at renderToStaticMarkup (/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom-server.browser.development.js:4074:27) at process (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1463:20) From previous event: at getMarkupFromTree (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1468:30) at getDataFromTree (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1452:12) at getDataFn (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:17989:81) at renderToStringWithData (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:17993:10) at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:18116:22 at processTicksAndRejections (internal/process/task_queues.js:97:5) From previous event: at _callee$ (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:18115:103) at tryCatch (/_v/public/assets/v1/npm/regenerator-runtime@0.11.1/runtime.js:63:40) at Generator.invoke [as _invoke] (/_v/public/assets/v1/npm/regenerator-runtime@0.11.1/runtime.js:297:22) at Generator.prototype.<computed> [as next] (/_v/public/assets/v1/npm/regenerator-runtime@0.11.1/runtime.js:115:21) at asyncGeneratorStep (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:294:24) at _next (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:316:9) at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:323:7 From previous event: at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:312:12 at render (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:18135:17) at Object.start (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:18218:30) at start (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:18964:35) at Module../react/index.tsx (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:18972:3) at __webpack_require__ (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:86:30) at requireEntry (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/index.js:14:10) at tryLoadModule (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:1710:13) at lazyLoad (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:1722:12) at register (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:1729:24) at Module.<anonymous> (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/index.js:19:136) at Module.../index.js (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/index.js:24:30) at __webpack_require__ (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:86:30) at checkDeferredModules (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:47:23) at Array.webpackJsonpCallback [as push] (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:34:19) at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/index.js:2:111 at Script.runInContext (vm.js:131:20) at VM.run (/usr/local/data/service/node_modules/vm2/lib/main.js:208:72) at /usr/src/node/middleware/render.ts:81:57"
"code":string"E_HTTP_400"
}
"message":string"Network error: Response not successful: Received status code 400"
"stackTrace":string"Error: Network error: Response not successful: Received status code 400 at new ApolloError (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:2759:28) at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:3941:40 at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:4253:25 at Set.forEach (<anonymous>) at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:4251:32 at Map.forEach (<anonymous>) at QueryManager.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/apollo-client/bundle.esm.js.QueryManager.broadcastQueries (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:4249:22) at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:3855:47 From previous event: at ObservableQuery.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/apollo-client/bundle.esm.js.ObservableQuery.result (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:2808:16) at QueryData.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/@apollo/react-hooks/lib/react-hooks.esm.js.QueryData.fetchData (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:814:44) at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1392:39 From previous event: at RenderPromises.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/@apollo/react-hooks/lib/react-hooks.esm.js.RenderPromises.addQueryPromise (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1391:64) at QueryData.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/@apollo/react-hooks/lib/react-hooks.esm.js.QueryData.getExecuteSsrResult (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:862:45) at QueryData.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/@apollo/react-hooks/lib/react-hooks.esm.js.QueryData.execute (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:793:21) at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1067:95 at useDeepMemo (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1041:42) at useBaseQuery (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1067:18) at useQuery (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1086:12) at Query (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:161:86) at processChild (/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom-server.browser.development.js:3195:14) at resolve (/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom-server.browser.development.js:3118:5) at ReactDOMServerRenderer.render (/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom-server.browser.development.js:3541:22) at ReactDOMServerRenderer.read (/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom-server.browser.development.js:3500:29) at renderToStaticMarkup (/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom-server.browser.development.js:4074:27) at process (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1463:20) From previous event: at getMarkupFromTree (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1468:30) at getDataFromTree (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1452:12) at getDataFn (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:17989:81) at renderToStringWithData (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:17993:10) at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:18116:22 at processTicksAndRejections (internal/process/task_queues.js:97:5) From previous event: at _callee$ (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:18115:103) at tryCatch (/_v/public/assets/v1/npm/regenerator-runtime@0.11.1/runtime.js:63:40) at Generator.invoke [as _invoke] (/_v/public/assets/v1/npm/regenerator-runtime@0.11.1/runtime.js:297:22) at Generator.prototype.<computed> [as next] (/_v/public/assets/v1/npm/regenerator-runtime@0.11.1/runtime.js:115:21) at asyncGeneratorStep (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:294:24) at _next (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:316:9) at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:323:7 From previous event: at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:312:12 at render (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:18135:17) at Object.start (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:18218:30) at start (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:18964:35) at Module../react/index.tsx (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:18972:3) at __webpack_require__ (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:86:30) at requireEntry (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/index.js:14:10) at tryLoadModule (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:1710:13) at lazyLoad (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:1722:12) at register (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:1729:24) at Module.<anonymous> (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/index.js:19:136) at Module.../index.js (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/index.js:24:30) at __webpack_require__ (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:86:30) at checkDeferredModules (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:47:23) at Array.webpackJsonpCallback [as push] (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:34:19) at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/index.js:2:111 at Script.runInContext (vm.js:131:20) at VM.run (/usr/local/data/service/node_modules/vm2/lib/main.js:208:72) at /usr/src/node/middleware/render.ts:81:57"
"forwardedPath":string"/"
"runtimeMeta":{2 items
"config":NULL
"version":string"8.124.3"
}
"page":string"store.home"
"status":int422
"errorReportMetadata":{2 items
"errorId":string"e966070dec7bc92e847bfd5d68a8c10c"
"reportCount":int0
}
"name":string"Error"
}
```

** Contexto adicional **
Não espero nem uma solução, espero o melhor para o ecossistema, e que seja reiniciado esse servidor zicado.
![2px](https://user-images.githubusercontent.com/73238487/99001360-7d357e80-2519-11eb-98a9-37e18dd83503.png)
![1px](https://user-images.githubusercontent.com/73238487/99001364-7f97d880-2519-11eb-94d0-90986dea8909.png)

**Comment by klzns** [comment]
Por favor manter a linguagem cordial e construtiva como diz no nosso [Código de Conduta](https://github.com/vtex-apps/store-discussion/blob/master/CODE_OF_CONDUCT.md).

O erro acontece por conta de chamada GraphQL feita no SSR que está dando erro:
![image](https://user-images.githubusercontent.com/284515/99006813-dacdc900-2521-11eb-86df-978e5c6a4195.png)

O erro acontece por conta do bloco `menu-item#more`. Foi salva um configuração no Site Editor para que ele seja do tipo `category`.

Abaixo mostra a propriedade `content` com as configurações salvas no Site Editor e `props` as configurações configuradas no tema.

![image](https://user-images.githubusercontent.com/284515/99007348-c9d18780-2522-11eb-995e-15be1852661c.png)

Uma forma de corrigir o problema seria trocar o id do bloco, como por exemplo `menu-item#mais`.

Vamos ver uma forma de ficar mais facil de identificar esse erro!

**Comment by brasiliadesigndf** [comment]
Obrigado por responder, porém ainda não consegui solucionar o problema.

Em qui., 12 de nov. de 2020 às 20:30, Breno Calazans <
notifications@github.com> escreveu:
