### ISSUE TITLE
Error `Store is not active` when linking

### ISSUE THREAD

**Issue by dapoz** [vtex-apps/store-discussion#484]
**Describe the bug**
We just setup a new account, installed `edition-store`, and when linking the new store theme it throws the error "Store is not active"

**To Reproduce**
https://dan--hoperesort.myvtex.com/

**Additional context**
```json
{
  "graphQLErrors": [
    {
      "message": "Request failed with status code 400",
      "path": [
        "products"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "message": "Request failed with status code 400",
          "name": "Error",
          "response": {
            "data": "Store 'hoperesort' is not active.",
            "headers": {
              "date": "Wed, 18 Nov 2020 14:01:55 GMT",
              "content-type": "text/html; charset=utf-8",
              "server": "VTEX IO",
              "content-length": "33",
              "etag": "W/\"21-I424HnjS2QCrl2poZeYJ+eutvJo\"",
              "vary": "Origin, Accept-Encoding",
              "access-control-allow-credentials": "true",
              "x-dns-prefetch-control": "off",
              "x-frame-options": "SAMEORIGIN",
              "strict-transport-security": "max-age=15552000; includeSubDomains",
              "x-download-options": "noopen",
              "x-content-type-options": "nosniff",
              "x-xss-protection": "1; mode=block",
              "x-request-id": "4438ba0d880847be84369e6202d3e189",
              "x-vtex-router-version": "9.0.1",
              "x-vtex-backend-status-code": "BadRequest",
              "x-vtex-backend-elapsed-time": "00:00:00.0494522",
              "x-vtex-router-elapsed-time": "00:00:00.0552914",
              "x-vtex-io-cluster-id": "devs-a"
            },
            "status": 400
          },
          "isAxiosError": true,
          "code": "E_HTTP_400"
        }
      },
      "name": "GraphQLError",
      "forwardedHost": "dan--hoperesort.myvtex.com",
      "forwardedProto": "http",
      "operationId": "4b52ed17-74f8-40a7-aa3b-3a4c54c4ad07",
      "query": {
        "query": "fragment ProductFragment on Product {\n  cacheId\n  productId\n  description\n  productName\n  productReference\n  linkText\n  brand\n  brandId\n  link\n  categories\n  priceRange {\n    sellingPrice {\n      highPrice\n      lowPrice\n      __typename\n    }\n    listPrice {\n      highPrice\n      lowPrice\n      __typename\n    }\n    __typename\n  }\n  specificationGroups {\n    name\n    originalName\n    specifications {\n      name\n      originalName\n      values\n      __typename\n    }\n    __typename\n  }\n  skuSpecifications {\n    field {\n      name\n      originalName\n      __typename\n    }\n    values {\n      name\n      originalName\n      __typename\n    }\n    __typename\n  }\n  productClusters {\n    id\n    name\n    __typename\n  }\n  clusterHighlights {\n    id\n    name\n    __typename\n  }\n  properties {\n    name\n    values\n    __typename\n  }\n}\n\nfragment ItemFragment on SKU {\n  itemId\n  name\n  nameComplete\n  complementName\n  ean\n  variations {\n    name\n    values\n    __typename\n  }\n  referenceId {\n    Key\n    Value\n    __typename\n  }\n  measurementUnit\n  unitMultiplier\n  images {\n    cacheId\n    imageId\n    imageLabel\n    imageTag\n    imageUrl\n    imageText\n    __typename\n  }\n}\n\nfragment SellerFragment on Seller {\n  sellerId\n  sellerName\n}\n\nfragment CommertialOfferFragment on Offer {\n  discountHighlights {\n    name\n    __typename\n  }\n  teasers {\n    name\n    conditions {\n      minimumQuantity\n      parameters {\n        name\n        value\n        __typename\n      }\n      __typename\n    }\n    effects {\n      parameters {\n        name\n        value\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  Price\n  ListPrice\n  Tax\n  taxPercentage\n  spotPrice\n  PriceWithoutDiscount\n  RewardValue\n  PriceValidUntil\n  AvailableQuantity\n}\n\nfragment InstallmentFragment on Installment {\n  Value\n  InterestRate\n  TotalValuePlusInterestRate\n  NumberOfInstallments\n  Name\n  PaymentSystemName\n}\n\nquery Products($category: String, $collection: String, $specificationFilters: [String], $orderBy: String, $from: Int, $to: Int, $hideUnavailableItems: Boolean = false, $skusFilter: ItemsFilter = ALL_AVAILABLE, $installmentCriteria: InstallmentsCriteria = MAX_WITHOUT_INTEREST) {\n  products(category: $category, collection: $collection, specificationFilters: $specificationFilters, orderBy: $orderBy, from: $from, to: $to, hideUnavailableItems: $hideUnavailableItems) {\n    ...ProductFragment\n    items(filter: $skusFilter) {\n      ...ItemFragment\n      sellers {\n        ...SellerFragment\n        commertialOffer {\n          ...CommertialOfferFragment\n          Installments(criteria: $installmentCriteria) {\n            ...InstallmentFragment\n            __typename\n          }\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n",
        "operationName": "Products",
        "variables": "{\"hideUnavailableItems\":false,\"category\":\"\",\"specificationFilters\":[],\"orderBy\":\"OrderByTopSaleDESC\",\"from\":0,\"to\":9}"
      },
      "requestId": "5c4fe62dc229473ba6fb4aa62ac6d9ac",
      "pathName": "products"
    }
  ],
  "networkError": null,
  "message": "GraphQL error: Request failed with status code 400",
  "stackTrace": "Error: GraphQL error: Request failed with status code 400\n    at new ApolloError (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:2759:28)\n    at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:3941:40\n    at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:4253:25\n    at Set.forEach (<anonymous>)\n    at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:4251:32\n    at Map.forEach (<anonymous>)\n    at QueryManager.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/apollo-client/bundle.esm.js.QueryManager.broadcastQueries (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:4249:22)\n    at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:4340:27\n    at Object.next (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:12229:23)\n    at notifySubscription (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:12051:18)\n    at onNotify (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:12086:3)\n    at SubscriptionObserver.next (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:12140:7)\n    at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:3560:75\n    at Set.forEach (<anonymous>)\n    at Object.next (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:3560:27)\n    at notifySubscription (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:12051:18)\nFrom previous event:\n    at ObservableQuery.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/apollo-client/bundle.esm.js.ObservableQuery.result (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:2808:16)\n    at QueryData.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/@apollo/react-hooks/lib/react-hooks.esm.js.QueryData.fetchData (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:814:44)\n    at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1392:39\nFrom previous event:\n    at RenderPromises.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/@apollo/react-hooks/lib/react-hooks.esm.js.RenderPromises.addQueryPromise (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1391:64)\n    at QueryData.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/@apollo/react-hooks/lib/react-hooks.esm.js.QueryData.getExecuteSsrResult (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:862:45)\n    at QueryData.push.../../../../modules/f8316c1c9c81cb63de4d295c626ce6998083a754dac1d3304bf076eb82fcc13a/dev/node_modules/@apollo/react-hooks/lib/react-hooks.esm.js.QueryData.execute (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:793:21)\n    at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1067:95\n    at useDeepMemo (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1041:42)\n    at useBaseQuery (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1067:18)\n    at useQuery (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1086:12)\n    at ProductSummaryList (/_v/public/assets/v1/published/vtex.product-summary@2.63.1/public/react/ProductSummaryList.js:118:80)\n    at processChild (/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom-server.browser.development.js:3195:14)\n    at resolve (/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom-server.browser.development.js:3118:5)\n    at ReactDOMServerRenderer.render (/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom-server.browser.development.js:3541:22)\n    at ReactDOMServerRenderer.read (/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom-server.browser.development.js:3500:29)\n    at renderToStaticMarkup (/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom-server.browser.development.js:4074:27)\n    at process (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1463:20)\nFrom previous event:\n    at getMarkupFromTree (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1468:30)\n    at getDataFromTree (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/apollo.js:1452:12)\n    at getDataFn (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:17989:81)\n    at renderToStringWithData (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:17993:10)\n    at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:18116:22\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\nFrom previous event:\n    at _callee$ (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:18115:103)\n    at tryCatch (/_v/public/assets/v1/npm/regenerator-runtime@0.11.1/runtime.js:63:40)\n    at Generator.invoke [as _invoke] (/_v/public/assets/v1/npm/regenerator-runtime@0.11.1/runtime.js:297:22)\n    at Generator.prototype.<computed> [as next] (/_v/public/assets/v1/npm/regenerator-runtime@0.11.1/runtime.js:115:21)\n    at asyncGeneratorStep (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:294:24)\n    at _next (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:316:9)\n    at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:323:7\nFrom previous event:\n    at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:312:12\n    at render (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:18135:17)\n    at Object.start (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:18218:30)\n    at start (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:18964:35)\n    at Module../react/index.tsx (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:18972:3)\n    at __webpack_require__ (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:86:30)\n    at requireEntry (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/index.js:14:10)\n    at tryLoadModule (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:1710:13)\n    at lazyLoad (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:1722:12)\n    at register (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:1729:24)\n    at Module.<anonymous> (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/index.js:19:136)\n    at Module.../index.js (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/index.js:24:30)\n    at __webpack_require__ (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:86:30)\n    at checkDeferredModules (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:47:23)\n    at Array.webpackJsonpCallback [as push] (/_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/common.js:34:19)\n    at /_v/public/assets/v1/published/vtex.render-runtime@8.124.3/public/react/index.js:2:111\n    at Script.runInContext (vm.js:131:20)\n    at VM.run (/usr/local/data/service/node_modules/vm2/lib/main.js:208:72)\n    at /usr/src/node/middleware/render.ts:81:57",
  "forwardedPath": "/",
  "runtimeMeta": {
    "config": null,
    "version": "8.124.3"
  },
  "page": "store.home",
  "status": 422,
  "errorReportMetadata": {
    "errorId": "430383e21a1fc1ae32bac31d1e0362c3",
    "reportCount": 0
  },
  "name": "Error"
}
```

**Comment by klzns** [comment]
Go to your admin => search => integration settings => start

**Comment by dapoz** [comment]
@klzns It's not working 
<img width="1016" alt="Screen Shot 2020-11-18 at 1 54 16 PM" src="https://user-images.githubusercontent.com/7804885/99561366-a173de00-29a5-11eb-9076-377403b7584c.png">

**Comment by LucasTornai** [comment]
I'm looking into it, will update here once I have an answer.

**Comment by LucasTornai** [comment]
@dapoz Should be fixed, can you try running it again?

**Comment by dapoz** [comment]
@LucasTornai It's fixed, thanks!

**Comment by Eddy-Huaylla** [comment]
Tuve el mismo error, gracias por la ayuda y pregunta.

**Comment by luiscvz** [comment]
Hola a todos!
Estamos con el mismo error, pero en el admin en integraciones no aparece la opción que tu adjuntas en la captura @dapoz  o que describes la ruta @klzns 😢

**Comment by matizarazaga** [comment]
Buen día!, estamos desarrollando nuestras primeras tiendas en VTEX IO y no contamos con las opciones dentro de "Configuraciones de la tienda": Búsqueda y GraphQL IDE... estas opciones se activan desde el administrador de VTEX o hay que solicitar a VTEX su habilitación?

**Comment by hermescortesm** [comment]
> Hola a todos!
> Estabamos con el mismo error, buscando en el admin en la sección de integraciones y no aparecía la opción que nombran, luego VTEX nos facilitó la ruta /admin/search/integration-settings

Esa ruta ya no funciona ¿verdad?

**Comment by shakeeranver** [comment]
Hi, 
I am having the same issue even after successfully linking with a workspace. May I know what was done to get this resolved?
Thanks

**Comment by hermescortesm** [comment]
Sup @shakeeranver you need deploy your work in the first branch and in that you can change with that route, finally you can deploy on your testing branch. But that route is on the "father" project

**Comment by shakeeranver** [comment]
Hi @hermescortesm thanks for the input. Unfortunately I am unable to follow :) - If I could kindly request to elaborate it would be very helpful. 
When you say deploy work in the first branch do you mean deploy the store theme from my current workspace to the master workspace?

**Comment by nahumocisita** [comment]
Gracias por la ayuda, también pude resolver el error que me marcaba.
